# Generated by Django 5.1.1 on 2024-09-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("websites", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="website",
            name="bytes_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="website",
            name="transition_count",
            field=models.IntegerField(default=0),
        ),
    ]
